### ISSUE TITLE
Use Number over Long/Double

### ISSUE THREAD

**Issue by atomicint** [mwanji/toml4j#11]
Perhaps change getLong(String) and getDouble(String) to getNumber(String) and add primitive accessors for better functionality.

```java
  public Number getNumber(String key) {
    return (Number) get(key);
  }

  public byte getByte(String key) {
    return getNumber(key).byteValue();
  }

  public short getShort(String key) {
    return getNumber(key).shortValue();
  }

  // ... and so on
```

**Comment by mwanji** [comment]
The rationale is that TOML specifies an Integer and Float that correspond to Java's Long and Double, respectively. While the naming is a bit weird, I tried to keep the Toml object as close as possible to the TOML primitives.

More specific types can be obtained with Long#intValue(), Long#shortValue(), etc. The Toml#to method allows binding to any Number subclass.

Also, in my experience, Number isn't commonly used or practical enough to justify adding 10 new methods (ie. getByte(String key) and getByte(String key, Byte defaultValue)).

Do you have any particular usage in mind?

**Comment by atomicint** [comment]
I have written this on my fork and updated tests to accommodate the changes, however this changes the functionality of TableArrayTest#should_parse_table_array line 29 when expecting null (because the key is not within table 1) to expect 0 instead. This may or may not need to be changed, I'd like to discuss an alternative solution.

View it here: https://github.com/atomicint/toml4j/tree/wip

While it is possible for more specific types to be achieved using Toml#to and Long#intValue, let's face it, it is simply not ideal to read or write, the extra syntax sugar is a nice touch and is pretty trivial to implement without breaking any of Toml's rules.

Also about Number not being practical, it doesn't have to be exposed outside of the API, limit its usage internally.

**Comment by mwanji** [comment]
Returning primitives is problematic, as missing keys can be requested. Currently, returning null is unambiguous because TOML does not support null. Returning 0 instead of null introduces ambiguity. If we use wrappers instead of primitives, then the only benefit is avoiding a cast, which I don't feel justifies adding so many new methods.

Post-1.0, if there really is demand, I'll consider it, but closing for now.
