### ISSUE TITLE
Add key and table existence checks

### ISSUE THREAD

**Issue by mwanji** [mwanji/toml4j#12]
Add the following methods to `Toml`:

* boolean contains(String key)
* boolean containsKey(String key)
* boolean containsTable(String key)
* boolean containsTableArray(String key)

key argument may be a plain or compound key (eg. "key" or "key.subKey").

contains returns true if the key exists.

containsXxx variants return true if the key exists and is of the specified type. Inline tables behave as tables.

**Comment by Zero3** [comment]
:+1:

**Comment by mwanji** [comment]
Implemented in https://github.com/mwanji/toml4j/commit/38666593dd1c4fe1eccbcdf7a8a39f15eb5ea378
