### ISSUE TITLE
Parsing exception messages contain trailing newlines

### ISSUE THREAD

**Issue by Zero3** [mwanji/toml4j#18]
Some of the parsing exceptions thrown by toml4j contains trailing newlines. This is somewhat unusual, and causes empty lines in log files when the exception messages are logged.

The offending newlines appear to be added at various places in https://github.com/mwanji/toml4j/blob/master/src/main/java/com/moandjiezana/toml/Results.java

**Comment by mwanji** [comment]
The idea was to be able to display multiple error messages at once. However, processing stops as soon as an error is encountered, so that's not even possible. Removing the newlines shouldn't be a problem, then.
