### ISSUE TITLE
toml throw ClassCastException

### ISSUE THREAD

**Issue by oyxiaogua** [mwanji/toml4j#27]
i'm use the following code to get table:
    `Toml toml = new Toml().read("[[a]]\nc=1\n[a.b]\nc=2");
    System.out.println(toml.getTable("a.b"));`

    the above code throws an exception:

    `java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at com.moandjiezana.toml.Toml.get(Toml.java:391)
	at com.moandjiezana.toml.Toml.getTable(Toml.java:211)`

     is "[[a]]\nc=1\n[a.b]\nc=2" legal? if not,why not throw an exception while parsing it.
   
    i want to get a.b.c value

     please ignore it if i'm wrong,thanks.

**Comment by mwanji** [comment]
I haven't tested this, but I think it's because a is an array of tables. Try "a[0].b".

**Comment by oyxiaogua** [comment]
i use toml.getLong("a[0].b.c") get the value ,thank you.
