### ISSUE TITLE
Allow to modify parsed Toml

### ISSUE THREAD

**Issue by gyscos** [mwanji/toml4j#28]
After parsing a Toml value, it is sometimes necessary to apply some post-processing, without mapping it to an actual class.
Adding methods to update (and maybe add) values would make this easier.

**Comment by mwanji** [comment]
I've been thinking about this, but feel resistant. The idea is to map a static configuration file to an immutable object. You can make it mutable by converting it to a Map.

Do you have any specific usecases in mind?

**Comment by Gyscos** [comment]
As said above, post-processing (applying rules like variable resolution, etc... that are not part of the toml standard) on the parsed value is my main use-case.
But altering a value before saving it back to disk (to edit the configuration for instance) could also be considered.

Anyway, I ended up using [TOML-javalib](https://github.com/TheElectronWill/TOML-javalib) instead, which directly gives a map.

**Comment by mwanji** [comment]
I've adressed this by adding a toMap() convenience method, available in v0.6.0 and described here: https://github.com/mwanji/toml4j#maps
