### ISSUE TITLE
Positive timezone offset in getDate()

### ISSUE THREAD

**Issue by aloyse** [mwanji/toml4j#31]
The following toml input
`date = 1966-12-12T00:00:00.001+01:00`
produces this exception
`IllegalStateException: Invalid value on line 1 : date = 1966-12-12T00:00:00.001`

In DateValueReaderWriter.java line 43 the '+' is missing ? 
`...
if (Character.isDigit(c) || c == '-' || c == ':' || c == '.' || c == 'T' || c == 'Z') {
...'
this explains the cutting off of '+01:00'

RFC3339 says: `time-numoffset    = ("+" / "-") time-hour [[":"] time-minute]` ..

Same Date with a negative TZ offset parses OK.

ag

**Comment by mwanji** [comment]
Thanks so much for pointing this out! It's fixed on master and will be on Maven Central soon.

**Comment by aloyse** [comment]
thanks for the quick reaction. i like your project !

**Comment by mwanji** [comment]
That's much appreciated! It's on Maven Central now, in case you haven't seen it.
