### ISSUE TITLE
Read existing toml objects

### ISSUE THREAD

**Issue by gustavkarlsson** [mwanji/toml4j#32]
I'm configuring my project with a default toml file, and then a user-created toml file that overwrites the defaults.

However, the user-created toml must currently be read as a File, InputStream or a String. I would love it to support reading other Toml objects too!

Example:
```java
Toml defaults = getDefaults()
Toml userConfig = getUserConfig()
Toml finalConfig = new Toml(defaults).read(userConfig);
```

**Comment by mwanji** [comment]
Would it be possible to have getUserConfig() return a File or InputStream? It feels odd to me to read an existing Toml object. Maybe a merge method that returns a new instance? I still need a little convincing... ;)

**Comment by gustavkarlsson** [comment]
Essentially, what I want is to set defaults from any source (File, String, Toml, InputStream) and then merge (overwrite) them with any other source (File, String, Toml, InputStream).

One typical case would be two files. One with defaults (bundled with the app) and one user-created.

Hope this helps in convincing you :)

**Comment by mwanji** [comment]
OK, as it doesn't really add API surface and extremely simple to implement, I've added it and am releasing it soon as 0.7.0. Thanks for the suggestion!

**Comment by gustavkarlsson** [comment]
Nice! Thanks a lot :)
