### ISSUE TITLE
Single quotes not allowed in the table name.

### ISSUE THREAD

**Issue by bruno-medeiros** [mwanji/toml4j#36]
I think single quotes are allowed in the table name (for [example](https://github.com/rust-lang-nursery/rustfmt/blob/5361f61/Cargo.toml#L35))  , just as double quotes, but this is not recognized in toml4j.

**Comment by mwanji** [comment]
Thanks for pointing this out. I just verified that this is indeed the case and will fix it very soon.

**Comment by mwanji** [comment]
I've released v0.7.1, it should be on Maven Central soon. Thanks again!
