### ISSUE TITLE
Way to iterate/extract arrays of inline tables?

### ISSUE THREAD

**Issue by keirlawson** [mwanji/toml4j#40]
It doesn't seem clear to me if there is a way using the toml4j API to iterate over arrays of inline tables, such as:

```toml
somekey = [
  { name = "foo" },
  { name = "bar" }
]
```

I did find a test that had an example using an array index in the key, however it feels like this is something that could be better surfaced in the API, or at least better documented?

**Comment by keirlawson** [comment]
My bad, getTables covers this

**Comment by mwanji** [comment]
Yes, it does, but I've long thought it was poorly named. I think it should be getTableArray. Any opinions?

**Comment by keirlawson** [comment]
Yea I think that would make it a little more obvious
