### ISSUE TITLE
Annotations with the name of the property

### ISSUE THREAD

**Issue by kirdeleg** [mwanji/toml4j#44]
Is there any possibility to specify property name if it is written with whitespace or hyphen?
If no, there is a good solution in Jakson: you can write annotation and set the right value.
If yes, please - add it to readme

**Comment by mwanji** [comment]
Do you mean when reading or writing? Can you give me an example?

**Comment by kirdeleg** [comment]
Yes, sure
I have such properties in my toml file:

node-id = "khfdaiq32-fd12-8420-2214-kafdli4328"
engine_version = "3"
start-date = "10m"
end-date = "3m"

And I map it to my Pojo class, where I have nodeId, engine_version, startDate and endDate variables.
But if I use such names for variables as above, all fields in my mapped object will be null, except engine_version, because it's name is similar to property in toml.

And unfortunately I can't change toml file at all

**Comment by mwanji** [comment]
I just tested it, and with the current version, Gson's SerializedName annotation is already supported. Have you tried that?

**Comment by jvtrigueros** [comment]
I just tried this with `@SerializedName` and can confirm that it works as expected.

**Comment by mwanji** [comment]
@jvtrigueros Thanks for testing it.

**Comment by sarimmehdi** [comment]
Why was this feature removed?
