### ISSUE TITLE
Support Inline-Tables

### ISSUE THREAD

**Issue by d3xter** [mwanji/toml4j#6]
Toml 0.3.1 spec supports Inline-Tables:

    [logger]
       sink = "FileSink"
       parameters = { file = "/home/user/file.log", logLevel = "Warning", fileSize = 32 }

**Comment by mwanji** [comment]
No, it doesn't. However, it seems fairly certain that the next version will.

**Comment by mwanji** [comment]
In case you need this quickly, I'll be implementing this on the [wip](https://github.com/mwanji/toml4j/tree/wip) branch. Test cases, in particular, are very welcome!

**Comment by mwanji** [comment]
This is now on on the wip branch. Please have a look to see if it works for you, @d3xter.

**Comment by d3xter** [comment]
It works as expected, thanks.
Should I add more test-cases?

**Comment by mwanji** [comment]
If you come up with some I haven't covered, please do! I'm working on fixing this uncommitted one: 

```toml
a = {}
[a]
```
which should fail, but doesn't.

**Comment by d3xter** [comment]
Alright, will have a look during the weekend into the test code and see if something is missing

**Comment by mwanji** [comment]
Thanks, much appreciated!

**Comment by mwanji** [comment]
This was released in v0.4.0
